'use client';
import {useMemo,useState} from 'react';
export function format(v:any,digits=4):string { if(v===null||v===undefined||Number.isNaN(v))return '—'; if(typeof v==='number')return Number.isInteger(v)&&Math.abs(v)>100? v.toLocaleString():v.toLocaleString(undefined,{maximumFractionDigits:digits}); return String(v); }
export default function Table({rows,columns,onRow,pageSize=50}:{rows:any[],columns?:{key:string,label:string}[],onRow?:(row:any)=>void,pageSize?:number}){
 const [sort,setSort]=useState('');const [descending,setDescending]=useState(true);const [query,setQuery]=useState('');const [page,setPage]=useState(0);
 const cols=columns??Object.keys(rows[0]??{}).filter(k=>typeof rows[0][k]!=='object').map(key=>({key,label:key.replaceAll('_',' ')}));
 const filtered=useMemo(()=>{let r=rows.filter(r=>!query||Object.values(r).join(' ').toLowerCase().includes(query.toLowerCase()));if(sort)r=[...r].sort((a,b)=>{const x=a[sort],y=b[sort];return (typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??'')))*(descending?-1:1);});return r;},[rows,sort,descending,query]);
 const safePage=Math.min(page,Math.max(0,Math.ceil(filtered.length/pageSize)-1));
 return <><div className="table-tools"><input aria-label="Filter table" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Filter rows…"/><span>{filtered.length.toLocaleString()} rows</span></div><div className="table-scroll"><table><thead><tr>{cols.map(c=><th key={c.key}><button onClick={()=>{setSort(c.key);setDescending(sort===c.key?!descending:true)}}>{c.label}{sort===c.key?(descending?' ↓':' ↑'):''}</button></th>)}</tr></thead><tbody>{filtered.slice(safePage*pageSize,(safePage+1)*pageSize).map((r,i)=><tr key={r.row_id??i} onClick={()=>onRow?.(r)} className={onRow?'clickable':''} tabIndex={onRow?0:undefined} onKeyDown={e=>{if(e.key==='Enter')onRow?.(r)}}>{cols.map(c=><td key={c.key} className={r[c.key]==='CHEAP'?'positive':r[c.key]==='RICH'?'negative':''}>{format(r[c.key])}</td>)}</tr>)}</tbody></table>{!filtered.length&&<div className="empty">No observations match these filters.</div>}</div><div className="pagination"><button disabled={safePage===0} onClick={()=>setPage(safePage-1)}>Previous</button><span>{safePage+1} / {Math.max(1,Math.ceil(filtered.length/pageSize))}</span><button disabled={(safePage+1)*pageSize>=filtered.length} onClick={()=>setPage(safePage+1)}>Next</button></div></>;
}
